cursor            #e2e5e2
cursor_text_color #616959

foreground            #fcfefe
background            #21251d
selection_foreground  #616959
selection_background  #e2e5e2
url_color             #e2e5e2

#: black 000000 767676
color0  #21251d
color8  #47503e
#: red cc0403 f2201f
color1  #0d86cd
color9  #0d86cd
#: green 19cb00 23fd00
color2  #86daea
color10 #86daea
#: yellow cecb00 fffd00
color3  #a99c53
color11 #a99c53
#: blue 0d73cc 1a8fff
color4  #6197af
color12 #6197af
#: magenta cb1ed1 fd28ff
color5  #c3ae84
color13 #c3ae84
#: cyan 0dcdcd 14ffff
color6  #62c2d8
color14 #62c2d8
#: white dddddd ffffff
color7  #bbe0e8
color15 #bbe0e8
