cursor            {{ base16.base06.dark.hex }}
cursor_text_color {{ base16.base01.dark.hex }}

foreground            {{ base16.base07.dark.hex }}
background            {{ base16.base00.dark.hex | lighten: -15.0 }}
selection_foreground  {{ base16.base01.dark.hex }}
selection_background  {{ base16.base06.dark.hex }}
url_color             {{ base16.base06.dark.hex }}

#: black 000000 767676
color0  {{ base16.base00.dark.hex | lighten: -15.0 }}
color8  {{ base16.base00.dark.hex }}
#: red cc0403 f2201f
color1  {{ base16.base08.dark.hex }}
color9  {{ base16.base08.dark.hex }}
#: green 19cb00 23fd00
color2  {{ base16.base0a.dark.hex }}
color10 {{ base16.base0a.dark.hex }}
#: yellow cecb00 fffd00
color3  {{ base16.base0b.dark.hex }}
color11 {{ base16.base0b.dark.hex }}
#: blue 0d73cc 1a8fff
color4  {{ base16.base0c.dark.hex }}
color12 {{ base16.base0c.dark.hex }}
#: magenta cb1ed1 fd28ff
color5  {{ base16.base0d.dark.hex }}
color13 {{ base16.base0d.dark.hex }}
#: cyan 0dcdcd 14ffff
color6  {{ base16.base09.dark.hex }}
color14 {{ base16.base09.dark.hex }}
#: white dddddd ffffff
color7  {{ base16.base0f.dark.hex }}
color15 {{ base16.base0f.dark.hex }}
